### ISSUE TITLE
Questions regarding evil-use-package.el usage

### ISSUE THREAD

**Issue by zzantares** [fbergroth/.emacs.d#1]
Hello, I'm getting started with `use-package` and your configuration turned out to be very useful, mainly because you're also using evil as I am, I hope you could help me since I'm having trouble with a special case and I didn't find an example in your configuration.

I was taking a look into [`evil-use-pacakge.el`](lisp/evil-use-package.el) but I'm not quite sure how to use it to translate this:

```elisp
(evil-define-key 'normal cider-repl-mode-map (kbd "C-a d") 'cider-quit)
(evil-define-key 'normal cider-docview-mode-map (kbd "q") 'zz-kill-buffer)
(evil-define-key 'normal cider-stacktrace-mode-map (kbd "q") 'zz-kill-buffer)

(evil-define-key 'insert cider-repl-mode-map (kbd "C-c C-d") 'cider-quit)
(evil-define-key 'insert cider-repl-mode-map (kbd "C-c C-c") 'cider-repl-kill-input)
(evil-define-key 'insert cider-repl-mode-map (kbd "C-p") 'cider-repl-previous-input)
(evil-define-key 'insert cider-repl-mode-map (kbd "C-n") 'cider-repl-next-input)
```

to `:evil-bind`

```elisp
(use-package cider
  :ensure t
  :evil-bind (normal ????? ))
```

My main questions are:

- How to define various key bindings in `normal` state to various maps (`cider-repl-mode-map`, `cider-docview-mode-map` and `cider-stacktrace-mode-map`)?
- How in the same `:evil-bind` definition  I could create bindings in `insert` state for `cider-repl-mode-map`?

Considering this should be defined on the `use-package cider` scope. Is it possible to do? What would be your approach in this case?

Thanks a lot for sharing your config! very helpful indeed!

**Comment by fbergroth** [comment]
Hey, this repo is pretty old, and I'm storing my emacs config elsewhere. `evil-use-package` was just a test, and I've abandoned it now. It was just a wrapper for `evil-leader`.

If you want something similar, I would suggest you try https://github.com/noctuid/general.el.

**Comment by zzantares** [comment]
Wow looks fantastic, didn't know about that package.

I'll try it. Thanks a lot! 👍
